In [28]:
import numpy as np
latent = np.load("latent.npy")
print(latent.shape)
import torch
a = torch.tensor(latent)


(1, 4, 28, 28)


In [29]:
import torch
import torchvision.transforms as transforms

# 定义一个形状为(1, 4, 28, 28)的tensor
tensor = torch.randn(1, 4, 28, 28)

# 定义transforms函数
normalize = transforms.Normalize(mean=[0.5, 0.5, 0.5,0.5], std=[0.5, 0.5, 0.5, 0.5])
denormalize = transforms.Normalize(mean=[-1, -1, -1, -1], std=[2, 2, 2, 2])

# 对tensor进行归一化
normalized_tensor = normalize(a)

# 还原原本的tensor
restored_tensor = denormalize(normalized_tensor)

In [46]:
import torch
import torchvision.transforms as transforms

def normalize(input_tensor):
    mean = input_tensor.mean(dim=(0, 2, 3))
    std = input_tensor.std(dim=(0, 2, 3))
    normalize = transforms.Normalize(mean, std)
    return normalize(input_tensor) ,mean ,std

def unnormalize(input_tensor, mean, std):
    unnormalize = transforms.Normalize(
    mean=-mean/std,
    std=1/std
)
    return unnormalize(input_tensor)

In [47]:
import numpy as np
latent = np.load("latent.npy")
print(latent.shape)
import torch
input_tensor = torch.tensor(latent)
output, mean,std = normalize(input_tensor)
unoutput = unnormalize(output,mean,std)

(1, 4, 28, 28)


In [52]:
output

tensor([[[[ 1.3613e+00,  4.7080e-01,  1.9474e+00,  ..., -1.7571e-03,
           -2.9533e-02,  3.5222e-01],
          [ 1.3833e+00,  1.1259e+00,  1.5214e+00,  ...,  5.9552e-01,
            1.3410e+00, -6.6134e-01],
          [ 1.3143e+00,  1.2799e+00,  1.2661e+00,  ..., -2.8962e-01,
            1.5292e+00,  1.1631e+00],
          ...,
          [-8.4720e-01, -1.8281e+00, -2.2511e+00,  ..., -7.9323e-03,
           -5.1528e-01,  2.8149e-01],
          [-1.1750e+00, -1.7587e+00, -3.1565e+00,  ..., -2.4771e-01,
           -1.5744e+00,  1.0699e+00],
          [-1.3897e+00, -2.0339e+00, -1.8714e+00,  ..., -8.9776e-01,
            1.1446e+00, -6.0042e-01]],

         [[ 3.5851e-01,  5.2435e-01,  1.7252e+00,  ..., -6.2710e-01,
            5.3622e-01,  8.4407e-01],
          [ 1.5760e+00,  9.2902e-01,  1.8221e+00,  ..., -3.2575e-01,
           -6.8178e-01,  9.0985e-01],
          [ 1.0112e-01,  9.3999e-01,  2.0779e+00,  ...,  2.3873e-01,
           -1.2023e+00,  8.1676e-01],
          ...,
     

In [49]:
unoutput 

tensor([[[[ 1.0382,  0.3469,  1.4931,  ..., -0.0199, -0.0414,  0.2549],
          [ 1.0552,  0.8554,  1.1624,  ...,  0.4437,  1.0224, -0.5319],
          [ 1.0016,  0.9749,  0.9643,  ..., -0.2433,  1.1685,  0.8843],
          ...,
          [-0.6761, -1.4375, -1.7659,  ..., -0.0247, -0.4185,  0.2000],
          [-0.9306, -1.3837, -2.4686,  ..., -0.2108, -1.2406,  0.8119],
          [-1.0972, -1.5972, -1.4712,  ..., -0.7154,  0.8699, -0.4846]],

         [[ 0.2080,  0.3467,  1.3511,  ..., -0.6163,  0.3567,  0.6141],
          [ 1.2263,  0.6852,  1.4321,  ..., -0.3643, -0.6621,  0.6692],
          [-0.0072,  0.6944,  1.6461,  ...,  0.1079, -1.0974,  0.5913],
          ...,
          [-0.3439, -2.2130, -1.7847,  ..., -0.4552,  0.6977,  0.1595],
          [-1.3061, -1.7076, -1.7966,  ..., -0.7345,  0.2012, -0.8417],
          [-1.7666, -1.8125, -1.0161,  ...,  0.6559, -0.1287, -0.1735]],

         [[-0.5708,  0.6680, -0.9507,  ...,  0.5036,  0.7575,  1.1882],
          [-0.0790, -0.4652, -

In [48]:
output

tensor([[[[ 1.3613e+00,  4.7080e-01,  1.9474e+00,  ..., -1.7571e-03,
           -2.9533e-02,  3.5222e-01],
          [ 1.3833e+00,  1.1259e+00,  1.5214e+00,  ...,  5.9552e-01,
            1.3410e+00, -6.6134e-01],
          [ 1.3143e+00,  1.2799e+00,  1.2661e+00,  ..., -2.8962e-01,
            1.5292e+00,  1.1631e+00],
          ...,
          [-8.4720e-01, -1.8281e+00, -2.2511e+00,  ..., -7.9323e-03,
           -5.1528e-01,  2.8149e-01],
          [-1.1750e+00, -1.7587e+00, -3.1565e+00,  ..., -2.4771e-01,
           -1.5744e+00,  1.0699e+00],
          [-1.3897e+00, -2.0339e+00, -1.8714e+00,  ..., -8.9776e-01,
            1.1446e+00, -6.0042e-01]],

         [[ 3.5851e-01,  5.2435e-01,  1.7252e+00,  ..., -6.2710e-01,
            5.3622e-01,  8.4407e-01],
          [ 1.5760e+00,  9.2902e-01,  1.8221e+00,  ..., -3.2575e-01,
           -6.8178e-01,  9.0985e-01],
          [ 1.0112e-01,  9.3999e-01,  2.0779e+00,  ...,  2.3873e-01,
           -1.2023e+00,  8.1676e-01],
          ...,
     